### ISSUE TITLE
Confirm my selection as soon as I am satisfied with the placement of my block.

### ISSUE THREAD

**Issue by turbodumba** [sopra-fs23-group-40/Client#13]

**Comment by thomi100** [comment]
https://github.com/sopra-fs23-group-40/Client/commit/76cfeacd31b17dd98c9445351248ce929ce28502
https://github.com/sopra-fs23-group-40/Client/commit/96a9a56f5d1e447a4964640c46570bc7f2be881c
https://github.com/sopra-fs23-group-40/Client/commit/ec561150819fce95672f05187a379a238cfc5a28
