### ISSUE TITLE
The inventory sometimes disappears when a turns is made or the game is refreshed.

### ISSUE THREAD

**Issue by thomi100** [sopra-fs23-group-40/Client#60]
The inventory is empty and does not show any blocks.
When clicking on the tiles, blocks can still be placed.
So this is "just" a visualization bug.

**Comment by Karo2222** [comment]
Figured out why through: 
https://github.com/sopra-fs23-group-40/Client/commit/51955c4399cd8452bd386a3f3bb6f5ef3befde1f

Fixed with:
https://github.com/sopra-fs23-group-40/Client/commit/01444a16e28c688919817e869b2c9dda47097aa7
