### ISSUE TITLE
Implement the option to choose a block out of your own inventory when it's your turn.

### ISSUE THREAD

**Issue by turbodumba** [sopra-fs23-group-40/Client#9]

**Comment by thomi100** [comment]
https://github.com/sopra-fs23-group-40/Client/commit/80f779ec473faad18e20755ceb96d806b24837bf
https://github.com/sopra-fs23-group-40/Client/commit/1bb857fae5f66be84e50c36979288f25b492d294
https://github.com/sopra-fs23-group-40/Client/commit/4debebe13729acdb398c59c73b22a38507dbc770
https://github.com/sopra-fs23-group-40/Client/commit/4deb99dccfe370fba5e1923ec510258cc6a9e38e
